
services:
  app:
    build: .
    container_name: go-chat-app
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gochatnet

  db:
    image: postgres:15
    container_name: go-chat-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gochatnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:latest
    command: -path /app/db/migrations -database ${DATABASE_URL} up
    volumes:
      - ./db/migrations:/app/db/migrations  
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    networks:
      - gochatnet

networks:
  gochatnet:
    driver: bridge

volumes:
  pgdata:
